### PR TITLE
Parser implementation

### PR DESCRIPTION
**Pull request by philipahlberg**

### CODE REVIEW

**Comment by philipahlberg** [comment]
I think the parser is in a good state now. It could use some more unit tests to ensure that it works as expected - perhaps one of you would be up to the task of writing some MicroC programs (ones that should parse as well as ones that shouldn't parse)?

We haven't discussed extensions to the language much. Some extensions I would propose which could open up for new features as well as simplify parsing would be:

- Allow index/field access on arbitrary expressions (syntactically)
This would make the language more in line with ordinary languages (such as C). It would require a semantic analysis to ensure index/field access is correct, though.
- Merge arithmetic and boolean expressions
This would require `boolean` types in addition to `int`. It wouldn't necessarily require *arbitrary* types, although that would be cool.
- Arbitrary field names in records
This is basically already possible in the parser - it would take just a few minimal changes to support syntactically. It would obviously change the analysis steps, but I think it would be cool to have.

Let me know what you think.

**Review by RikkeGrabski — APPROVED** [review]
I can add some more tests, I'm thinking of using the examples that is also used by pa4fun.

**Comment by philipahlberg** [comment]
> 
> 
> I can add some more tests, I'm thinking of using the examples that is also used by pa4fun.

Good idea. I suggest writing a test along the lines of the ones already present. Even writing the expected AST could be a good way to get a feel for the AST types - I'll help you out if you have any questions.

**Comment by Projectattic** [comment]
Hey, I'm sorry it took so long to reply - I've been very busy this week. I'll take a closer look at the code over the holiday. I'd also be happy to write some MicroC tests.

**Comment by philipahlberg** [comment]
> 
> 
> Hey, I'm sorry it took so long to reply - I've been very busy this week. I'll take a closer look at the code over the holiday. I'd also be happy to write some MicroC tests.

Sounds good. I think I'll merge this branch now, and then you guys can make separate branches (based off of `main`) for these tests (and fixes, if needed). @RikkeGrabski I noticed you already made a branch for your tests - I'm fairly sure you can simply change the merge target when you make the pull request, so it shouldn't be a problem.

**Pull request merged**
